### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by dannyvankooten** [neonmoe/minreq#25]
Hello,

Thank you for putting this crate out there, I love the simple API for simple Rust programs.

When using this crate with the HTTPS feature enabled, I am getting the following error for this specific URL I am testing. It works for other URL's, but somehow connecting to this particular server fails. 

I'm not sure how to debug this further, but hopefully the following is useful for you.

```rust
fn main() {
    let response = minreq::get("https://www.iex.nl/Beleggingsfonds-Koers/61114463/Vanguard-FTSE-All-World-UCITS-ETF.aspx").send().expect("Error fetching HTML");
}
```

```
$ RUST_BACKTRACE=full ./target/debug/vwrl 

thread 'main' panicked at 'Error fetching HTML: IoError(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })', src/main.rs:7:20
stack backtrace:
   0:     0x55ecd94178e4 - backtrace::backtrace::libunwind::trace::hd3cb661800925418
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55ecd94178e4 - backtrace::backtrace::trace_unsynchronized::h64b171cb1575b1ef
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55ecd94178e4 - std::sys_common::backtrace::_print_fmt::h3b631ab3a555d066
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x55ecd94178e4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h958356a888a9d47f
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55ecd9435f3c - core::fmt::write::h2d61f5c0328557bc
                               at src/libcore/fmt/mod.rs:1057
   5:     0x55ecd94147a7 - std::io::Write::write_fmt::h0410c63bf2aeeef0
                               at src/libstd/io/mod.rs:1426
   6:     0x55ecd9419985 - std::sys_common::backtrace::_print::hef794572a53c64d7
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55ecd9419985 - std::sys_common::backtrace::print::h3fc3a5e9c940e80e
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55ecd9419985 - std::panicking::default_hook::{{closure}}::h3e7698b7b1d66f6c
                               at src/libstd/panicking.rs:204
   9:     0x55ecd9419671 - std::panicking::default_hook::h5728e803511699ca
                               at src/libstd/panicking.rs:224
  10:     0x55ecd9419f8a - std::panicking::rust_panic_with_hook::h254ad17cf54d371c
                               at src/libstd/panicking.rs:472
  11:     0x55ecd9419b70 - rust_begin_unwind
                               at src/libstd/panicking.rs:380
  12:     0x55ecd94348d1 - core::panicking::panic_fmt::h157efb1de94e218e
                               at src/libcore/panicking.rs:85
  13:     0x55ecd94346f3 - core::option::expect_none_failed::h2f37193330a95f9a
                               at src/libcore/option.rs:1198
  14:     0x55ecd9025e72 - core::result::Result<T,E>::expect::hdda15be9e234232a
                               at /rustc/48840618382eccb8a799320c8e5d08e3b52f4c42/src/libcore/result.rs:990
  15:     0x55ecd9021a38 - vwrl::main::hb5a44bbb096dada5
                               at src/main.rs:7
  16:     0x55ecd90263b0 - std::rt::lang_start::{{closure}}::hd0431b761e50a1e6
                               at /rustc/48840618382eccb8a799320c8e5d08e3b52f4c42/src/libstd/rt.rs:67
  17:     0x55ecd9419a53 - std::rt::lang_start_internal::{{closure}}::hcc1a2b66a85e517f
                               at src/libstd/rt.rs:52
  18:     0x55ecd9419a53 - std::panicking::try::do_call::h6e00bbd8754db59b
                               at src/libstd/panicking.rs:305
  19:     0x55ecd941cc17 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  20:     0x55ecd941a430 - std::panicking::try::h656a1c74080d7a83
                               at src/libstd/panicking.rs:281
  21:     0x55ecd941a430 - std::panic::catch_unwind::hf379374ddffee909
                               at src/libstd/panic.rs:394
  22:     0x55ecd941a430 - std::rt::lang_start_internal::h8bf94f6480420edb
                               at src/libstd/rt.rs:51
  23:     0x55ecd9026389 - std::rt::lang_start::h301862297bf0bd6c
                               at /rustc/48840618382eccb8a799320c8e5d08e3b52f4c42/src/libstd/rt.rs:67
  24:     0x55ecd9022cea - main
  25:     0x7f876cd71153 - __libc_start_main
  26:     0x55ecd902116e - _start
  27:                0x0 - <unknown>
```

**Comment by neonmoe** [comment]
Not sure what's going on here, but I've narrowed the error down to the `rustls::StreamOwned::write` call during `send`. Maybe the server just drops requests that don't have some specific headers, or something?

**Comment by dannyvankooten** [comment]
I did some more digging, the issue doesn't seem header specific:

```rust
minreq::get("https://www.iex.nl")
        .with_header("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:74.0) Gecko/20100101 Firefox/74.0")
        .with_header("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8")
        .with_header("Connection", "keep-alive")
        .with_header("Accept-Language", "en-US,en;q=0.5")
        .with_header("Accept-Encoding", "gzip, deflate, br")
        .with_header("Host", "www.iex.nl")
        .with_header("Cache-Control", "max-age=0")
        .with_header("Upgrade-Insecure-Requests", "1")
        .send()
        .unwrap();
```

So to rule out an issue with minreq I tried to replicate using `reqwest` with `rustls`, which got me the same issue:

```rust
reqwest::Client::builder()
        .use_rustls_tls()
        .build()
        .unwrap()
        .get("https://www.iex.nl/")
        .send()
        .await
        .unwrap()
        .text()
        .await
        .unwrap();
```

So I'm fairly certain this is in rusttls and probably by design (server doesn't use any ciphersuites supported by rusttls) , looking at ctz/rustls#333.

Nothing to see here then, moving on. Thanks for looking into this though!
